# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 00:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=24, verbose_name='order ID')),
                ('shipping_nr', models.CharField(blank=True, max_length=32, null=True, verbose_name='shipping number')),
                ('brief', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('shipping_date', models.DateField(blank=True, db_index=True, null=True)),
                ('arrival_date', models.DateField(blank=True, db_index=True, null=True)),
                ('complete', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=16, unique=True)),
                ('sort', models.IntegerField(db_index=True)),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('order_url', models.CharField(db_index=True, max_length=255, verbose_name='order URL')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ordertracking.State'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordertracking.Store'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('store', 'order_id')]),
        ),
    ]
