# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordertracking', '0002_initial_states'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_date', '-id')},
        ),
    ]
