# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordertracking', '0004_rename_arrival_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('store', 'order_id', 'order_date')]),
        ),
    ]
