# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-17 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertracking', '0005_order_unique_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, db_index=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(blank=True, db_index=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_nr',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='shipping number'),
        ),
    ]
