# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertracking', '0006_order_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
