# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertracking', '0008_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='price'),
        ),
    ]
