# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertracking', '0009_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='last shipping status'),
        ),
    ]
