# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordertracking', '0003_better_order_ordering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='arrival_date',
            new_name='delivery_date',
        ),
    ]
